author = "Nico"
baseurl = "https://npadula.com/blog/"
canonifyurls = true
copyright = ""
paginate = 5
title = "nico.txt"
publishDir = "docs"

[params]
copyright = ""
copyrightUrl = ""
description = ""
faviconfile = ""
latestpostcount = 5
logofile = ""
highlightjs = true
highlightjslanguages = [ "bash", "css", "diff", "django", "javascript", "python", "yaml" ]
toc = true
posts_navigation = true
progressively = true
flattr = ""
github = "npadula"
gitlab = ""
linkedin = ""
telegram = ""
twitter = ""
mastodon_url = ""
email = ""

[[params.best_posts]]
title = "Foundations & Intuition: Programming and Music"
url = "/posts/foundations-intuition-programming-music/"

[[params.best_posts]]
title = "MOOCs: Done, Doing, Will Do"
url = "/posts/moocs-done-doing-will-do/"



# [[params.best_posts]]
# title = "Test test"
# url = "/blog/t/"

[[menu.primary]]
identifier = "archive"
name = "Archive"
url = "/posts/"
weight = 10

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

# [[menu.primary]]
# identifier = "patreon"
# name = "CV"
# url = "https://npadula.com"
# weight = 100

[[menu.secondary]]
identifier = "patreon"
name = "CV"
url = "https://npadula.com"
weight = 200


[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
